name: Create new release

on: push

jobs:
  create-release:
    name: "Build and Release"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Build limpet"
        run: |
          sudo apt install musl-dev musl-tools gcc-aarch64-linux-gnu
          sh ./package.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*.zip"
